### ISSUE TITLE
Python wrapper for Image class

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#123]
1. Add a python wrapper for `Image` class in which we are able to call member functions of `Image` class. Put new code in `src/python` folder.
2. Add a simple example of using new Python code and put it in `example/python/image`.

Relates to #103

**Comment by MatthewMcGonagle** [comment]
I've played around a little bit with making C extensions of python, and I'm interested in try to make progress on this issue. Just to clarify, you want the extension to be built using the distutils python module? As in [the description in the python docs](https://docs.python.org/3/extending/building.html#building-c-and-c-extensions-with-distutils)?

**Comment by ihhub** [comment]
Looks like yes. Ideally we should compile it in Travis-vi but this is another topic of discussion.

**Comment by ngetahun** [comment]
I suggest using swig. I've been playing with this issue over the weekend. @MatthewMcGonagle do you have another suggestion?

**Comment by MatthewMcGonagle** [comment]
@ngetahun I'm not familiar with swig. I was thinking about just doing it manually according to the [instructions in the pydocs](https://docs.python.org/3/extending/newtypes_tutorial.html), but swig sounds like it is easier.

**Comment by ngetahun** [comment]
Ok cool. You can also look at the tensorflow repo on how they generate their python library [here](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/python). All the `*.i` files are swig interface files.

**Comment by ihhub** [comment]
If you are out of ideas where and what exactly to import please ask me. I'll guide you with this.

**Comment by MatthewMcGonagle** [comment]
Sorry to not get back with a comment for a while. I was just getting more familiar with the swig as that seems to be the best solution. It looks like python's distutils can handle swig files directly; hopefully we just need to pass in swig_options = ['-c++'] to distutils.core.Extension(), [see section 2.3.2 of the docs for distutils](https://docs.python.org/3/distutils/setupscript.html).

**Comment by MatthewMcGonagle** [comment]
Short question: when using swig, rvalue constructors such as `ImageTemplate(ImageTemplate &&)` come up as warning that they will be ignored since they make no sense in Python. Is it better to just not put them in the swig interface file (so there are no warnings, but the interface file is less complete for other interfacing)?

**Comment by MatthewMcGonagle** [comment]
Another question: `Image::data()` should be overwritten in swig using `%extend` to return a list type compatible with python. Should it return a numpy array or just python lists?

**Comment by ihhub** [comment]
Python of course doesn't support move-constructors so we could do not include these methods.
`Image::data()` returns a raw pointer to an allocated array. I don't think we need to return a whole array as this data brings no sense to developer.

**Comment by MatthewMcGonagle** [comment]
What type of example for `Image` are you thinking of? What I have so far is that I have also created wrappers for `Bitmap_Operation::Save()` and `Bitmap_Operation::Load()` and (from python) am able to open `mercury.bmp` and then save a copy `mercury2.bmp`.

**Comment by ihhub** [comment]
If you have done `Bitmap` conversion then I would recommend to have a look into `examples/bitmap_operation` as it should be easy to implement.

**Comment by MatthewMcGonagle** [comment]
Okay, I have enough to implement `examples/bitmap_operation`. I decided to just manually re-implement custom exceptions from image_exception.h as python code inside the swig file; it just seemed easiest to do it that way since `image_exception.h` isn't very large. Is that alright for now?

Also, I'm not seeing much point in doing both `method1()` and `method2()`  of `example_bitmap_operation.cpp` in python, so I'm just just going to do `method1()` appropriately renamed.

I'll work on getting everything nice, in the proper place, and add some `README.md` files to the python directory.

**Comment by ihhub** [comment]
Regarding `image_exception.h`: yes it is okay. Any solution is better than no solution at all.

Yes, you are right. There is no sense to make 2 methods for the example.
