### ISSUE TITLE
OpenCL implementation of IsEqual() function

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#451]
We have CPU implementation of **IsEqual**() function in `src/image_function.h` and `src/image_function.cpp` files. We want to add OpenCL implementation of the same function. Please put new code in `src/opencl/image_function_opencl.h` and `src/opencl/image_function_opencl.cpp` files. Things which we need to do:
1. Copy 2 function declarations from `src/image_function.h` to `src/opencl/image_function_opencl.h`
2. Copy first function implementation from `src/image_function.cpp` to `src/opencl/image_function_opencl.cpp`
3. Add OpenCL kernel called `isEqualOpenCL` into unnamed namespace at the top of `src/opencl/image_function_opencl.cpp` file
4. Add second function implementation by following **Invert()** code logic

**Comment by manekenpix** [comment]
I'll take this one if that's ok.

**Comment by ihhub** [comment]
@manekenpix sure! Please do not hesitate to ask any questions if you have any.

**Comment by manekenpix** [comment]
@ihhub sorry for the late response, I got caught up with some stuff, but I'm now working on this issue.

I have a question about step 3:

This is my first time working with OpenCL. I read about it [here](https://leonardoaraujosantos.gitbooks.io/opencl/content/chapter1.html) and I think I understand how OpenCL kernels do parallel computing. I assume `isEqual` will use an OpenCL kernel to perform a parallel comparison between 2 images, and I was wondering about the standard way in OpenCL to return a value to the function calling the kernel since kernels return void and the parameters passed to them are usually information about the images themselves (StartXIn, Offset, Width, Height...).
I was thiking about passing a variable to the kernel that would store a specific value if the comparison fails and then return false in the caller, but I'm not sure if that can be done with kernels.

Any guidance would be very appreciated.

**Comment by ihhub** [comment]
I think the answer for your questions lies [here](https://github.com/ihhub/penguinV/blob/master/test/unit_tests/opencl/unit_test_helper_opencl.cpp) :)

**Comment by manekenpix** [comment]
Thank you! This is perfect.
