### ISSUE TITLE
Rename functions for CUDA unit tests

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#540]
We have unit tests for CUDA stored in `test/unit_tests/cuda/unit_test_image_function_cuda.cpp` file. We would like to rename all functions to have better naming. We need to rename from **FunctionNameXParametersTest** into **FunctionNameFormYTest**. For example `AbsoluteDifference2ParametersTest` should be renamed into `AbsoluteDifferenceForm1Test`. Simple as it is.

**Comment by josephnicholas** [comment]
Can I take this task please? @ihhub

**Comment by ihhub** [comment]
Sure!

**Comment by josephnicholas** [comment]
@ihhub thanks! Will add me as assignee please?

**Comment by ihhub** [comment]
@josephnicholas I can't make it for issue but I always do for pull request.

**Comment by josephnicholas** [comment]
@ihhub Ok will work on this. Thanks.

**Comment by josephnicholas** [comment]
@ihhub sorry for the newbie question, since I don't have much experience with GPU programming, do I need to have a NVIDIA GPU to install CUDA libraries for the Unit tests? Because my MAC has only AMD GPU which I think is OPENCL supported, but with this task is it a need to do it in an NVIDIA GPU env?

I am still in the compiling side. :)

**Comment by ihhub** [comment]
@josephnicholas you can do not even have CUDA at your PC. Once you submit pull request our CI pipeline will automatically compile your CUDA code. If it would have a problem CI pipeline would highlight this and I can point if something wrong with code.
